-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:9847f52ea92317d6c26ac78bd0655d38:761dd9d2d621563362960be5ff8c5343:332d7df0c7c7642f0cdb7f5fa7b9fa52$
-- 

return {
	texture = 'mainchar_pieces.png',
	frames = {
			{
				name = "01.png",
				spriteColorRect = { x = 0, y = 0, width = 243, height = 130 },
				uvRect = { u0 = 0.00619195, v0 = 0.22453, u1 = 0.758514, v1 = 0.353116 },
				spriteSourceSize = { width = 243, height = 130 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "02.png",
				spriteColorRect = { x = 0, y = 0, width = 119, height = 86 },
				uvRect = { u0 = 0.399381, v0 = 0.676558, u1 = 0.767802, v1 = 0.761622 },
				spriteSourceSize = { width = 119, height = 86 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "03.png",
				spriteColorRect = { x = 0, y = 0, width = 129, height = 63 },
				uvRect = { u0 = 0.00619195, v0 = 0.591494, u1 = 0.405573, v1 = 0.653808 },
				spriteSourceSize = { width = 129, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "04.png",
				spriteColorRect = { x = 0, y = 0, width = 148, height = 81 },
				uvRect = { u0 = 0.00619195, v0 = 0.424332, u1 = 0.464396, v1 = 0.504451 },
				spriteSourceSize = { width = 148, height = 81 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "05.png",
				spriteColorRect = { x = 0, y = 0, width = 247, height = 95 },
				uvRect = { u0 = 0.00619195, v0 = 0.128586, u1 = 0.770898, v1 = 0.222552 },
				spriteSourceSize = { width = 247, height = 95 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "06.png",
				spriteColorRect = { x = 0, y = 0, width = 162, height = 68 },
				uvRect = { u0 = 0.00619195, v0 = 0.355094, u1 = 0.50774, v1 = 0.422354 },
				spriteSourceSize = { width = 162, height = 68 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "07.png",
				spriteColorRect = { x = 0, y = 0, width = 278, height = 126 },
				uvRect = { u0 = 0.00619195, v0 = 0.00197824, u1 = 0.866873, v1 = 0.126607 },
				spriteSourceSize = { width = 278, height = 126 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "08.png",
				spriteColorRect = { x = 0, y = 0, width = 138, height = 84 },
				uvRect = { u0 = 0.00619195, v0 = 0.506429, u1 = 0.433437, v1 = 0.589515 },
				spriteSourceSize = { width = 138, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "09.png",
				spriteColorRect = { x = 0, y = 0, width = 83, height = 81 },
				uvRect = { u0 = 0.272446, v0 = 0.915925, u1 = 0.52322, v1 = 0.998022 },
				spriteSourceSize = { width = 83, height = 81 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "10.png",
				spriteColorRect = { x = 0, y = 0, width = 105, height = 65 },
				uvRect = { u0 = 0.773994, v0 = 0.705242, u1 = 0.975232, v1 = 0.8091 },
				spriteSourceSize = { width = 105, height = 65 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "11.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 31 },
				uvRect = { u0 = 0.798762, v0 = 0.916914, u1 = 0.95356, v1 = 0.947577 },
				spriteSourceSize = { width = 50, height = 31 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "12.png",
				spriteColorRect = { x = 0, y = 0, width = 27, height = 66 },
				uvRect = { u0 = 0.773994, v0 = 0.676558, u1 = 0.978328, v1 = 0.703264 },
				spriteSourceSize = { width = 27, height = 66 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "13.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 57 },
				uvRect = { u0 = 0.690402, v0 = 0.7636, u1 = 0.767802, v1 = 0.81998 },
				spriteSourceSize = { width = 25, height = 57 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "14.png",
				spriteColorRect = { x = 0, y = 0, width = 102, height = 55 },
				uvRect = { u0 = 0.352941, v0 = 0.801187, u1 = 0.668731, v1 = 0.855589 },
				spriteSourceSize = { width = 102, height = 55 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "16.png",
				spriteColorRect = { x = 0, y = 0, width = 97, height = 93 },
				uvRect = { u0 = 0.439628, v0 = 0.582591, u1 = 0.739938, v1 = 0.67458 },
				spriteSourceSize = { width = 97, height = 93 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "17.png",
				spriteColorRect = { x = 0, y = 0, width = 125, height = 46 },
				uvRect = { u0 = 0.00619195, v0 = 0.655786, u1 = 0.393189, v1 = 0.701286 },
				spriteSourceSize = { width = 125, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "18.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 35 },
				uvRect = { u0 = 0.798762, v0 = 0.949555, u1 = 0.907121, v1 = 0.984174 },
				spriteSourceSize = { width = 35, height = 35 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "19.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 107 },
				uvRect = { u0 = 0.352941, v0 = 0.7636, u1 = 0.684211, v1 = 0.799209 },
				spriteSourceSize = { width = 36, height = 107 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "20.png",
				spriteColorRect = { x = 0, y = 0, width = 78, height = 64 },
				uvRect = { u0 = 0.513932, v0 = 0.423343, u1 = 0.755418, v1 = 0.486647 },
				spriteSourceSize = { width = 78, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "21.png",
				spriteColorRect = { x = 0, y = 0, width = 72, height = 75 },
				uvRect = { u0 = 0.764706, v0 = 0.276954, u1 = 0.987616, v1 = 0.351137 },
				spriteSourceSize = { width = 72, height = 75 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "22.png",
				spriteColorRect = { x = 0, y = 0, width = 73, height = 50 },
				uvRect = { u0 = 0.764706, v0 = 0.225519, u1 = 0.990712, v1 = 0.274975 },
				spriteSourceSize = { width = 73, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "23.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 36 },
				uvRect = { u0 = 0.594427, v0 = 0.857567, u1 = 0.656347, v1 = 0.893175 },
				spriteSourceSize = { width = 20, height = 36 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "24.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 51 },
				uvRect = { u0 = 0.427245, v0 = 0.857567, u1 = 0.482972, v1 = 0.908012 },
				spriteSourceSize = { width = 18, height = 51 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "25.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 53 },
				uvRect = { u0 = 0.272446, v0 = 0.803165, u1 = 0.343653, v1 = 0.855589 },
				spriteSourceSize = { width = 23, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "26.png",
				spriteColorRect = { x = 0, y = 0, width = 49, height = 57 },
				uvRect = { u0 = 0.26935, v0 = 0.857567, u1 = 0.421053, v1 = 0.913947 },
				spriteSourceSize = { width = 49, height = 57 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "27.png",
				spriteColorRect = { x = 0, y = 0, width = 69, height = 68 },
				uvRect = { u0 = 0.764706, v0 = 0.353116, u1 = 0.978328, v1 = 0.420376 },
				spriteSourceSize = { width = 69, height = 68 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "28.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 37 },
				uvRect = { u0 = 0.873065, v0 = 0.121662, u1 = 0.987616, v1 = 0.136499 },
				spriteSourceSize = { width = 15, height = 37 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "29.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 25 },
				uvRect = { u0 = 0.00619195, v0 = 0.88724, u1 = 0.0526316, v1 = 0.911968 },
				spriteSourceSize = { width = 15, height = 25 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "30.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 35 },
				uvRect = { u0 = 0.594427, v0 = 0.895153, u1 = 0.650155, v1 = 0.929772 },
				spriteSourceSize = { width = 18, height = 35 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "31.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 50 },
				uvRect = { u0 = 0.489164, v0 = 0.857567, u1 = 0.588235, v1 = 0.907023 },
				spriteSourceSize = { width = 32, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "32.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 46 },
				uvRect = { u0 = 0.873065, v0 = 0.00197824, u1 = 0.993808, v1 = 0.0474777 },
				spriteSourceSize = { width = 39, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "33.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 71 },
				uvRect = { u0 = 0.873065, v0 = 0.049456, u1 = 0.987616, v1 = 0.119683 },
				spriteSourceSize = { width = 37, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "34.png",
				spriteColorRect = { x = 0, y = 0, width = 96, height = 94 },
				uvRect = { u0 = 0.674923, v0 = 0.821958, u1 = 0.972136, v1 = 0.914936 },
				spriteSourceSize = { width = 96, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "35.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 76 },
				uvRect = { u0 = 0.76161, v0 = 0.422354, u1 = 0.993808, v1 = 0.497527 },
				spriteSourceSize = { width = 75, height = 76 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "36.png",
				spriteColorRect = { x = 0, y = 0, width = 84, height = 81 },
				uvRect = { u0 = 0.00619195, v0 = 0.916914, u1 = 0.266254, v1 = 0.997033 },
				spriteSourceSize = { width = 84, height = 81 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "37.png",
				spriteColorRect = { x = 0, y = 0, width = 87, height = 93 },
				uvRect = { u0 = 0.470588, v0 = 0.488625, u1 = 0.739938, v1 = 0.580613 },
				spriteSourceSize = { width = 87, height = 93 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "38.png",
				spriteColorRect = { x = 0, y = 0, width = 83, height = 83 },
				uvRect = { u0 = 0.00619195, v0 = 0.803165, u1 = 0.263158, v1 = 0.885262 },
				spriteSourceSize = { width = 83, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "39.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 77 },
				uvRect = { u0 = 0.74613, v0 = 0.623145, u1 = 0.98452, v1 = 0.67458 },
				spriteSourceSize = { width = 52, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "40.png",
				spriteColorRect = { x = 0, y = 0, width = 67, height = 78 },
				uvRect = { u0 = 0.513932, v0 = 0.355094, u1 = 0.755418, v1 = 0.421365 },
				spriteSourceSize = { width = 67, height = 78 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "41.png",
				spriteColorRect = { x = 0, y = 0, width = 86, height = 69 },
				uvRect = { u0 = 0.77709, v0 = 0.138477, u1 = 0.990712, v1 = 0.223541 },
				spriteSourceSize = { width = 86, height = 69 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "42.png",
				spriteColorRect = { x = 0, y = 0, width = 85, height = 51 },
				uvRect = { u0 = 0.529412, v0 = 0.931751, u1 = 0.79257, v1 = 0.982196 },
				spriteSourceSize = { width = 85, height = 51 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "43.png",
				spriteColorRect = { x = 0, y = 0, width = 123, height = 77 },
				uvRect = { u0 = 0.74613, v0 = 0.499505, u1 = 0.98452, v1 = 0.621167 },
				spriteSourceSize = { width = 123, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "44.png",
				spriteColorRect = { x = 0, y = 0, width = 110, height = 99 },
				uvRect = { u0 = 0.00619195, v0 = 0.703264, u1 = 0.346749, v1 = 0.801187 },
				spriteSourceSize = { width = 110, height = 99 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

