-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:d76d8c713c141d7410f0090f3cc92bb6:89aedfd80bfef7249bb9c9f09aaf0110:332d7df0c7c7642f0cdb7f5fa7b9fa52$
-- 

return {
	texture = 'mainchar_pieces.png',
	frames = {
			{
				name = "01.png",
				spriteColorRect = { x = 0, y = 0, width = 243, height = 130 },
				uvRect = { u0 = 0.00526316, v0 = 0.434995, u1 = 0.644737, v1 = 0.562072 },
				spriteSourceSize = { width = 243, height = 130 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "02.png",
				spriteColorRect = { x = 0, y = 0, width = 119, height = 86 },
				uvRect = { u0 = 0.642105, v0 = 0.662757, u1 = 0.955263, v1 = 0.746823 },
				spriteSourceSize = { width = 119, height = 86 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "03.png",
				spriteColorRect = { x = 0, y = 0, width = 129, height = 63 },
				uvRect = { u0 = 0.65, v0 = 0.552297, u1 = 0.989474, v1 = 0.613881 },
				spriteSourceSize = { width = 129, height = 63 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "04.png",
				spriteColorRect = { x = 0, y = 0, width = 148, height = 81 },
				uvRect = { u0 = 0.00526316, v0 = 0.632454, u1 = 0.394737, v1 = 0.711632 },
				spriteSourceSize = { width = 148, height = 81 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "05.png",
				spriteColorRect = { x = 0, y = 0, width = 247, height = 95 },
				uvRect = { u0 = 0.00526316, v0 = 0.340176, u1 = 0.655263, v1 = 0.43304 },
				spriteSourceSize = { width = 247, height = 95 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "06.png",
				spriteColorRect = { x = 0, y = 0, width = 162, height = 68 },
				uvRect = { u0 = 0.00526316, v0 = 0.564027, u1 = 0.431579, v1 = 0.630499 },
				spriteSourceSize = { width = 162, height = 68 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "07.png",
				spriteColorRect = { x = 0, y = 0, width = 278, height = 126 },
				uvRect = { u0 = 0.00526316, v0 = 0.215054, u1 = 0.736842, v1 = 0.338221 },
				spriteSourceSize = { width = 278, height = 126 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "08.png",
				spriteColorRect = { x = 0, y = 0, width = 138, height = 84 },
				uvRect = { u0 = 0.00526316, v0 = 0.713587, u1 = 0.368421, v1 = 0.795699 },
				spriteSourceSize = { width = 138, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "09.png",
				spriteColorRect = { x = 0, y = 0, width = 83, height = 81 },
				uvRect = { u0 = 0.231579, v0 = 0.918866, u1 = 0.45, v1 = 0.998045 },
				spriteSourceSize = { width = 83, height = 81 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "10.png",
				spriteColorRect = { x = 0, y = 0, width = 105, height = 65 },
				uvRect = { u0 = 0.00526316, v0 = 0.797654, u1 = 0.281579, v1 = 0.861193 },
				spriteSourceSize = { width = 105, height = 65 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "11.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 31 },
				uvRect = { u0 = 0.286842, v0 = 0.797654, u1 = 0.368421, v1 = 0.84653 },
				spriteSourceSize = { width = 50, height = 31 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "12.png",
				spriteColorRect = { x = 0, y = 0, width = 27, height = 66 },
				uvRect = { u0 = 0.660526, v0 = 0.340176, u1 = 0.731579, v1 = 0.404692 },
				spriteSourceSize = { width = 27, height = 66 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "13.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 57 },
				uvRect = { u0 = 0.660526, v0 = 0.406647, u1 = 0.726316, v1 = 0.462366 },
				spriteSourceSize = { width = 25, height = 57 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "14.png",
				spriteColorRect = { x = 0, y = 0, width = 102, height = 55 },
				uvRect = { u0 = 0.00526316, v0 = 0.863148, u1 = 0.273684, v1 = 0.916911 },
				spriteSourceSize = { width = 102, height = 55 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "15.png",
				spriteColorRect = { x = 0, y = 0, width = 294, height = 216 },
				uvRect = { u0 = 0.00526316, v0 = 0.00195503, u1 = 0.778947, v1 = 0.213099 },
				spriteSourceSize = { width = 294, height = 216 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "16.png",
				spriteColorRect = { x = 0, y = 0, width = 97, height = 93 },
				uvRect = { u0 = 0.736842, v0 = 0.349951, u1 = 0.992105, v1 = 0.44086 },
				spriteSourceSize = { width = 97, height = 93 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "17.png",
				spriteColorRect = { x = 0, y = 0, width = 125, height = 46 },
				uvRect = { u0 = 0.644737, v0 = 0.615836, u1 = 0.973684, v1 = 0.660802 },
				spriteSourceSize = { width = 125, height = 46 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "18.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 35 },
				uvRect = { u0 = 0.818421, v0 = 0.942326, u1 = 0.910526, v1 = 0.97654 },
				spriteSourceSize = { width = 35, height = 35 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "19.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 107 },
				uvRect = { u0 = 0.634211, v0 = 0.748778, u1 = 0.915789, v1 = 0.783969 },
				spriteSourceSize = { width = 36, height = 107 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "20.png",
				spriteColorRect = { x = 0, y = 0, width = 78, height = 64 },
				uvRect = { u0 = 0.784211, v0 = 0.0694037, u1 = 0.989474, v1 = 0.131965 },
				spriteSourceSize = { width = 78, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "21.png",
				spriteColorRect = { x = 0, y = 0, width = 72, height = 75 },
				uvRect = { u0 = 0.792105, v0 = 0.785924, u1 = 0.989474, v1 = 0.856305 },
				spriteSourceSize = { width = 72, height = 75 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "22.png",
				spriteColorRect = { x = 0, y = 0, width = 73, height = 50 },
				uvRect = { u0 = 0.792105, v0 = 0.85826, u1 = 0.984211, v1 = 0.907136 },
				spriteSourceSize = { width = 73, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "23.png",
				spriteColorRect = { x = 0, y = 0, width = 20, height = 36 },
				uvRect = { u0 = 0.921053, v0 = 0.748778, u1 = 0.973684, v1 = 0.783969 },
				spriteSourceSize = { width = 20, height = 36 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "24.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 51 },
				uvRect = { u0 = 0.286842, v0 = 0.848485, u1 = 0.334211, v1 = 0.898338 },
				spriteSourceSize = { width = 18, height = 51 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "25.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 53 },
				uvRect = { u0 = 0.65, v0 = 0.480938, u1 = 0.710526, v1 = 0.532747 },
				spriteSourceSize = { width = 23, height = 53 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "26.png",
				spriteColorRect = { x = 0, y = 0, width = 49, height = 57 },
				uvRect = { u0 = 0.657895, v0 = 0.85435, u1 = 0.786842, v1 = 0.910068 },
				spriteSourceSize = { width = 49, height = 57 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "27.png",
				spriteColorRect = { x = 0, y = 0, width = 69, height = 68 },
				uvRect = { u0 = 0.605263, v0 = 0.785924, u1 = 0.786842, v1 = 0.852395 },
				spriteSourceSize = { width = 69, height = 68 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "28.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 37 },
				uvRect = { u0 = 0.278947, v0 = 0.900293, u1 = 0.376316, v1 = 0.914956 },
				spriteSourceSize = { width = 15, height = 37 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "29.png",
				spriteColorRect = { x = 0, y = 0, width = 15, height = 25 },
				uvRect = { u0 = 0.65, v0 = 0.464321, u1 = 0.715789, v1 = 0.478983 },
				spriteSourceSize = { width = 15, height = 25 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "30.png",
				spriteColorRect = { x = 0, y = 0, width = 18, height = 35 },
				uvRect = { u0 = 0.381579, v0 = 0.894428, u1 = 0.473684, v1 = 0.912023 },
				spriteSourceSize = { width = 18, height = 35 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "31.png",
				spriteColorRect = { x = 0, y = 0, width = 32, height = 50 },
				uvRect = { u0 = 0.818421, v0 = 0.909091, u1 = 0.95, v1 = 0.940371 },
				spriteSourceSize = { width = 32, height = 50 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "32.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 46 },
				uvRect = { u0 = 0.339474, v0 = 0.85435, u1 = 0.460526, v1 = 0.892473 },
				spriteSourceSize = { width = 39, height = 46 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "33.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 71 },
				uvRect = { u0 = 0.465789, v0 = 0.85435, u1 = 0.652632, v1 = 0.890518 },
				spriteSourceSize = { width = 37, height = 71 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "34.png",
				spriteColorRect = { x = 0, y = 0, width = 96, height = 94 },
				uvRect = { u0 = 0.742105, v0 = 0.256109, u1 = 0.994737, v1 = 0.347996 },
				spriteSourceSize = { width = 96, height = 94 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "35.png",
				spriteColorRect = { x = 0, y = 0, width = 75, height = 76 },
				uvRect = { u0 = 0.436842, v0 = 0.616813, u1 = 0.636842, v1 = 0.690127 },
				spriteSourceSize = { width = 75, height = 76 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "36.png",
				spriteColorRect = { x = 0, y = 0, width = 84, height = 81 },
				uvRect = { u0 = 0.00526316, v0 = 0.918866, u1 = 0.226316, v1 = 0.998045 },
				spriteSourceSize = { width = 84, height = 81 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "37.png",
				spriteColorRect = { x = 0, y = 0, width = 87, height = 93 },
				uvRect = { u0 = 0.4, v0 = 0.692082, u1 = 0.628947, v1 = 0.782991 },
				spriteSourceSize = { width = 87, height = 93 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "38.png",
				spriteColorRect = { x = 0, y = 0, width = 83, height = 83 },
				uvRect = { u0 = 0.594737, v0 = 0.912023, u1 = 0.813158, v1 = 0.993157 },
				spriteSourceSize = { width = 83, height = 83 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "39.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 77 },
				uvRect = { u0 = 0.436842, v0 = 0.564027, u1 = 0.639474, v1 = 0.614858 },
				spriteSourceSize = { width = 52, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "40.png",
				spriteColorRect = { x = 0, y = 0, width = 67, height = 78 },
				uvRect = { u0 = 0.784211, v0 = 0.00195503, u1 = 0.989474, v1 = 0.0674487 },
				spriteSourceSize = { width = 67, height = 78 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "41.png",
				spriteColorRect = { x = 0, y = 0, width = 86, height = 69 },
				uvRect = { u0 = 0.373684, v0 = 0.784946, u1 = 0.6, v1 = 0.852395 },
				spriteSourceSize = { width = 86, height = 69 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "42.png",
				spriteColorRect = { x = 0, y = 0, width = 85, height = 51 },
				uvRect = { u0 = 0.455263, v0 = 0.913979, u1 = 0.589474, v1 = 0.997067 },
				spriteSourceSize = { width = 85, height = 51 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "43.png",
				spriteColorRect = { x = 0, y = 0, width = 123, height = 77 },
				uvRect = { u0 = 0.784211, v0 = 0.13392, u1 = 0.986842, v1 = 0.254154 },
				spriteSourceSize = { width = 123, height = 77 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "44.png",
				spriteColorRect = { x = 0, y = 0, width = 110, height = 99 },
				uvRect = { u0 = 0.731579, v0 = 0.442815, u1 = 0.992105, v1 = 0.550342 },
				spriteSourceSize = { width = 110, height = 99 },
				spriteTrimmed = false,
				textureRotated = true
			},
		}
	}

