-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:3fdfac60aafa018c59da0a7582d999d3$
-- 

return {
	texture = 'boy_sheet.png',
	frames = {
			{
				name = "arm.png",
				spriteColorRect = { x = 0, y = 0, width = 132, height = 97 },
				uvRect = { u0 = 0.546875, v0 = 0.431641, u1 = 0.925781, v1 = 0.689453 },
				spriteSourceSize = { width = 132, height = 97 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "body.png",
				spriteColorRect = { x = 0, y = 0, width = 128, height = 136 },
				uvRect = { u0 = 0.0078125, v0 = 0.431641, u1 = 0.539062, v1 = 0.681641 },
				spriteSourceSize = { width = 128, height = 136 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "boot.png",
				spriteColorRect = { x = 0, y = 0, width = 88, height = 82 },
				uvRect = { u0 = 0.0078125, v0 = 0.685547, u1 = 0.351562, v1 = 0.845703 },
				spriteSourceSize = { width = 88, height = 82 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "hand.png",
				spriteColorRect = { x = 0, y = 0, width = 65, height = 65 },
				uvRect = { u0 = 0.0078125, v0 = 0.849609, u1 = 0.261719, v1 = 0.976562 },
				spriteSourceSize = { width = 65, height = 65 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "head.png",
				spriteColorRect = { x = 0, y = 0, width = 217, height = 235 },
				uvRect = { u0 = 0.0078125, v0 = 0.00390625, u1 = 0.925781, v1 = 0.427734 },
				spriteSourceSize = { width = 217, height = 235 },
				spriteTrimmed = false,
				textureRotated = true
			},
			{
				name = "leg.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 78 },
				uvRect = { u0 = 0.269531, v0 = 0.849609, u1 = 0.574219, v1 = 0.941406 },
				spriteSourceSize = { width = 47, height = 78 },
				spriteTrimmed = false,
				textureRotated = true
			},
		}
	}

